### ISSUE TITLE
Zooming in image

### ISSUE THREAD

**Issue by chges100** [Steffenhir/Background_extraction#24]
OS: Ubuntu 20.04
Program version: v0.0.5 (tested with master branch and conda environment, too)

For some pictures it would be good if zooming into the image is possible for a more precise positioning of the sample points.

Edit: Seems to be a problem under Linux OS.

**Comment by Steffenhir** [comment]
Zooming with the mouse wheel should already work. Does it not work on Linux ?

**Comment by chges100** [comment]
With Linux (Ubuntu 20.04) nothing happens when scrolling with the wheel - there does not even show up a message or exception in the terminal. When clicking with the mousewheel, nothing happens, too.

Panning the image with left mouse button and setting points with the right works properly, in the opposite.

**Comment by chges100** [comment]
Should be fixed with PR #25
