### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by chges100** [Steffenhir/Background_extraction#6]
System: Ubuntu Linux 20.04
Branch: main@e533e536e73a34b5f4894046289275766917c54e

Found a few (small) UI issues:

- Moving the sliders translates the picture to left/right simultanously
- The Font is rather pixelelated - maybe TKinter has an option for TrueType?

**Comment by Steffenhir** [comment]
Fixed the first issue in feature/gui branch, not sure how to fix second one

**Comment by chges100** [comment]
Had a short look onto this - it is possible to change the default font in Tkinter, but it does not look good anyway (tried two different font types). It seems it is a problem with Linux and Tkinter since with Windows everything is fine.
